[package]
name = "model"
version = "0.1.0"
authors = ["Alex Weber <lexwbr@gmail.com>"]
edition = "2021"

[dependencies]
aws-sdk-dynamodb = "0.19.0"
serde = "1.0.145"
chrono = "0.4.22"
chrono-tz = "0.8.2"
bdays = "0.1.3"
