[package]
name = "model"
version = "0.1.0"
authors = ["Alex Weber <lexwbr@gmail.com>"]
edition = "2021"

[dependencies]
aws-sdk-dynamodb = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
tracing = { workspace = true }
bdays = "0.1.3"
