[workspace]
members = [
    "migrate",
    "response",
    "authorizer",
    "repository",
    "schedule-get",
    "schedule-update",
    "slack",
    "slack-usergroup-users-update",
    "hero-list",
    "hero-get",
    "user-create",
    "model"
]
