[workspace]
members = [
    "lambdas/hero-list",
    "lambdas/hero-get",
    "lambdas/custom-authorizer",
    "lambdas/schedule-get",
    "lambdas/user-create",
    "lambdas/schedule-update",
    "lambdas/slack-usergroup-users-update",
    "repository",
    "response",
    "slack",
    "model"
]
