[package]
name = "custom-authorizer"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2.13", features = ["full"] }
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime" }
serde_json = "1.0"
google-signin = "0.3.0"